import "../styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SideBar from "../components/sideBar/SideBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ft_trancendence",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SideBar />
        <div>{children}</div>
      </body>
    </html>
  );
}
