import "../styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SideBar from "../components/sideBar/SideBar";
import NavBar from "@/components/navBar/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ft_trancendence",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col">
        <NavBar />
        </div>
        <div className="flex flex-row w-screen bg-slate-200 ">
        <div className=" hidden 2xl:block m-0 transition-2 ">
        <SideBar />
        </div>
        <div className="w-screen 2xl:pl-32 m-0 bg-color-main">{children}</div>
        </div>
      </body>
    </html>
  );
}
