version: '3.8'

services:

  database:
    image: postgres:13 
    container_name: app-database
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=db
    networks:
      - mynetwork
    restart: always

  backend:
    container_name: app-backend
    build: ./backend 
    ports:
      - '4000:4000' 
    depends_on:
      - database
    networks:
      - mynetwork
    env_file:
      - ./backend/.env
    restart: always

   

  frontend:
    container_name: app-frontend
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
    restart: always






networks:
  mynetwork:
volumes:
  postgres:



