version: '3.8'

services:

  database:
    container_name: app-database
    image: postgres:13 
    ports:
      - '5432:5432'
    env_file:
      - .env
    networks:
      - mynetwork
    volumes:
      - ./database:/var/lib/postgresql/data
    restart: always

  backend:
    container_name: app-backend
    build: ./backend 
    ports:
      - '4000:4000' 
    depends_on:
      - database
    networks:
      - mynetwork
    env_file:
      - .env
    restart: always

  frontend:
    container_name: app-frontend
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
    env_file:
      - ./frontend/.env.local
    restart: always

networks:
  mynetwork:
    driver: bridge



