version: '3.8'

services:
  db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: postgres
  adminer:
    image: adminer
    ports:
      - 8080:8080