version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    
    depends_on:
      - backend
    restart: always

  backend:
    build: ./backend 
    ports:
      - '4000:4000' 
    depends_on:
      - database
    networks:
      - mynetwork
    env_file:
      - ./backend/.env
    restart: always


  database:
    image: postgres:13 
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: db
    networks:
      - mynetwork
    restart: always


networks:
  mynetwork:




